name: Django CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        sudo apt-get install libcups2-dev
        pip install pycups
        pip install mysqlclient
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: autopep8
      uses: peter-evans/autopep8@v2.0.0
      with:
        args: . --recursive --exclude='*/migrations/*' "/cancer_subject/"
    - name: Run Tests
      run: |
        python manage.py test
